% ============================================================
%  IEEE-Format Figure: Max AoI vs Number of Active Beams
%  B=1 to B=7, log y-axis focused on low AoI region
%  Legend top-left, axes start from origin edge
%  K=4/cell, T=200, N_mc=500, R_th=12 Mbps, C=12
% ============================================================

close all; clear; clc;

% ── Data (B=1 to B=7) ───────────────────────────────────────
B = 1:7;

max_aoi_greedy   = [12.132, 6.272, 4.620, 4.102, 4.074, 5.262, 14.300];
max_aoi_rr       = [12.518, 7.286, 5.866, 4.812, 5.970,  8.060, 23.330];
max_aoi_periodic = [23.022,11.036, 7.314, 6.046, 5.600,  8.510, 22.430];
max_aoi_random   = [37.890,18.594,12.556, 9.754, 9.088, 10.198, 24.508];

% ── Optimal B* ───────────────────────────────────────────────
[~, idx_g] = min(max_aoi_greedy);
[~, idx_r] = min(max_aoi_rr);
[~, idx_p] = min(max_aoi_periodic);
[~, idx_n] = min(max_aoi_random);

% ── Colors ───────────────────────────────────────────────────
% Greedy   → blue        (primary, proposed method)
% RR       → teal/green  (was orange — now clearly distinct from periodic)
% Periodic → red/vermil  (was yellow — now clearly distinct from RR)
% Random   → purple      (unchanged)
col_greedy   = [0,   114, 178] / 255;   % blue
col_rr       = [0,   158, 115] / 255;   % teal-green  #009E73
col_periodic = [213,  94,   0] / 255;   % vermillion  #D55E00
col_random   = [150,  60, 180] / 255;   % purple

% ── Figure: IEEE single-column 3.5 x 3.0 inches ─────────────
fig = figure('Units','inches', ...
             'Position',[1 1 3.5 3.0], ...
             'Color','white');

ax = axes('Parent', fig, ...
          'Position', [0.14, 0.13, 0.82, 0.78]);
hold(ax, 'on');

% ── Plot lines ───────────────────────────────────────────────
h_g = semilogy(ax, B, max_aoi_greedy, ...
    'Color',           col_greedy, ...
    'LineStyle',       '--', ...
    'LineWidth',       1.1, ...
    'Marker',          'o', ...
    'MarkerSize',      4.0, ...
    'MarkerFaceColor', col_greedy, ...
    'MarkerEdgeColor', 'white', ...
    'DisplayName',     'Greedy max-AoI');

h_r = semilogy(ax, B, max_aoi_rr, ...
    'Color',           col_rr, ...
    'LineStyle',       ':', ...
    'LineWidth',       1.1, ...
    'Marker',          's', ...
    'MarkerSize',      4.0, ...
    'MarkerFaceColor', col_rr, ...
    'MarkerEdgeColor', 'white', ...
    'DisplayName',     'Round Robin');

h_p = semilogy(ax, B, max_aoi_periodic, ...
    'Color',           col_periodic, ...
    'LineStyle',       '-.', ...
    'LineWidth',       1.1, ...
    'Marker',          '^', ...
    'MarkerSize',      4.0, ...
    'MarkerFaceColor', col_periodic, ...
    'MarkerEdgeColor', 'white', ...
    'DisplayName',     'Periodic Hopping');

h_n = semilogy(ax, B, max_aoi_random, ...
    'Color',           col_random, ...
    'LineStyle',       '-', ...
    'LineWidth',       1.1, ...
    'Marker',          'd', ...
    'MarkerSize',      4.0, ...
    'MarkerFaceColor', col_random, ...
    'MarkerEdgeColor', 'white', ...
    'DisplayName',     'Random');

% ── Optimal B* pentagon markers ──────────────────────────────
semilogy(ax, B(idx_g), max_aoi_greedy(idx_g), ...
    'Marker','p','MarkerSize',6, ...
    'MarkerFaceColor', col_greedy, ...
    'MarkerEdgeColor', [0.15 0.15 0.15], ...
    'LineStyle','none','LineWidth',0.9, ...
    'HandleVisibility','off');

semilogy(ax, B(idx_r), max_aoi_rr(idx_r), ...
    'Marker','p','MarkerSize',6, ...
    'MarkerFaceColor', col_rr, ...
    'MarkerEdgeColor', [0.15 0.15 0.15], ...
    'LineStyle','none','LineWidth',0.9, ...
    'HandleVisibility','off');

semilogy(ax, B(idx_p), max_aoi_periodic(idx_p), ...
    'Marker','p','MarkerSize',6, ...
    'MarkerFaceColor', col_periodic, ...
    'MarkerEdgeColor', [0.15 0.15 0.15], ...
    'LineStyle','none','LineWidth',0.9, ...
    'HandleVisibility','off');

semilogy(ax, B(idx_n), max_aoi_random(idx_n), ...
    'Marker','p','MarkerSize',6, ...
    'MarkerFaceColor', col_random, ...
    'MarkerEdgeColor', [0.15 0.15 0.15], ...
    'LineStyle','none','LineWidth',0.9, ...
    'HandleVisibility','off');

h_opt = semilogy(ax, NaN, NaN, ...
    'Marker','p','MarkerSize',6, ...
    'MarkerFaceColor', [0.45 0.45 0.45], ...
    'MarkerEdgeColor', [0.15 0.15 0.15], ...
    'LineStyle','none','LineWidth',0.9, ...
    'DisplayName','Optimal $B^\star$');

hold(ax, 'off');

% ── Y-axis: log scale ────────────────────────────────────────
ax.YScale               = 'log';
ax.YLim                 = [3.5, 45];
ax.YTick                = [4, 5, 6, 7, 8, 10, 12, 15, 20, 25, 35];
ax.YTickLabel           = {'4','5','6','7','8','10','12','15','20','25','35'};
ax.YMinorTick           = 'off';

% ── X-axis ───────────────────────────────────────────────────
ax.XLim                 = [1, 7];
ax.XTick                = 1:7;
ax.XTickLabel           = {'1','2','3','4','5','6','7'};
ax.XLimitMethod         = 'tight';
ax.YLimitMethod         = 'padded';

% ── General axes formatting ──────────────────────────────────
ax.FontName             = 'Times New Roman';
ax.FontSize             = 9;
ax.TickLabelInterpreter = 'latex';
ax.Box                  = 'on';
ax.LineWidth            = 0.9;
ax.XGrid                = 'on';
ax.YGrid                = 'on';
ax.GridLineStyle        = '-';
ax.GridAlpha            = 0.22;
ax.GridColor            = [0.60 0.60 0.60];
ax.TickDir              = 'in';
ax.TickLength           = [0.015 0.015];
ax.Layer                = 'top';

% ── Axis labels ──────────────────────────────────────────────
xlabel(ax, '$B$', ...
    'Interpreter','latex', ...
    'FontName','Times New Roman', ...
    'FontSize',9);

ylabel(ax, 'Max AoI', ...
    'Interpreter','latex', ...
    'FontName','Times New Roman', ...
    'FontSize',9);

% ── Legend ───────────────────────────────────────────────────
leg = legend(ax, [h_g, h_r, h_p, h_n, h_opt], ...
    'Interpreter',  'latex', ...
    'FontName',     'Times New Roman', ...
    'FontSize',     7.0, ...
    'Location',     'northwest', ...
    'Box',          'on', ...
    'EdgeColor',    [0.55 0.55 0.55], ...
    'LineWidth',    0.7, ...
    'Color',        'white', ...
    'NumColumns',   1);
leg.ItemTokenSize = [18, 5];

drawnow;
lpos      = leg.Position;
lpos(3)   = max(lpos(3), 0.35);
lpos(1)   = ax.Position(1) + 0.015;
lpos(2)   = ax.Position(2) + ax.Position(4) - lpos(4) - 0.015;
leg.Position = lpos;

% ── Export ───────────────────────────────────────────────────
set(fig,'PaperUnits','inches','PaperSize',[3.5 3.0], ...
    'PaperPosition',[0 0 3.5 3.0]);

print(fig,'fig_maxAoI_vs_B_log','-dpdf','-r600');
print(fig,'fig_maxAoI_vs_B_log','-dpng','-r600');
print(fig,'fig_maxAoI_vs_B_log','-depsc','-r600');

fprintf('Saved: fig_maxAoI_vs_B_log.pdf / .png / .eps\n');
fprintf('\nOptimal B* per policy:\n');
fprintf('  Greedy   : B*=%d  MaxAoI=%.3f\n', B(idx_g), max_aoi_greedy(idx_g));
fprintf('  RR       : B*=%d  MaxAoI=%.3f\n', B(idx_r), max_aoi_rr(idx_r));
fprintf('  Periodic : B*=%d  MaxAoI=%.3f\n', B(idx_p), max_aoi_periodic(idx_p));
fprintf('  Random   : B*=%d  MaxAoI=%.3f\n', B(idx_n), max_aoi_random(idx_n));